# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: >
  Unicorn Properties Service. Validate the content, images and contract of property listings.

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - ES4000 # Rule disabled because the CatchAll Rule doesn't need a DLQ
        - ES6000 # Rule disabled because SQS DLQs don't need a RedrivePolicy
        - E0001 # Rule disabled because cfn-lint cannot parse SAM Policy templates without arguments (ComprehendBasicAccessPolicy, RekognitionDetectOnlyPolicy)
        - WS2001 # Rule disabled because check does not support !ToJsonString transform
        - ES1001 # Rule disabled because our Lambda functions don't need DestinationConfig.OnFailure
        - W3002 # Rule disabled as nested templates are being packaged

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Mappings:
  LogsRetentionPeriodMap:
    local:
      Days: 3
    dev:
      Days: 3
    prod:
      Days: 14
  Constants:
    ProjectName:
      Value: "AWS Serverless Developer Experience"

Conditions:
  IsProd: !Equals [!Ref Stage, Prod]


Resources:
  #### CLOUDFORMATION NESTED STACKS
  # CloudFormation Stack with the Properties Service Event Registry and Schemas
  EventSchemasStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: "integration/event-schemas.yaml"
      Parameters:
        Stage: !Ref Stage

  # CloudFormation Stack with the Cross-service EventBus policy for Properties Service
  SubscriberPoliciesStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    DependsOn:
      - UnicornPropertiesEventBusNameParam
    Properties:
      Location: "integration/subscriber-policies.yaml"
      Parameters:
        Stage: !Ref Stage

  # CloudFormation Stack with the Cross-service EventBus Rules for Properties Service
  SubscriptionsStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    DependsOn:
      - UnicornPropertiesEventBusArnParam
    Properties:
      Location: "integration/subscriptions.yaml"
      Parameters:
        Stage: !Ref Stage

Outputs:
  #### DYNAMODB OUTPUTS
  ContractStatusTableName:
    Description: DynamoDB table storing contract status information
    Value: !Ref ContractStatusTable

  #### LAMBDA FUNCTIONS OUTPUTS
  ContractStatusChangedHandlerFunctionName:
    Value: !Ref ContractStatusChangedHandlerFunction
  ContractStatusChangedHandlerFunctionArn:
    Value: !GetAtt ContractStatusChangedHandlerFunction.Arn

  PropertiesApprovalSyncFunctionName:
    Value: !Ref PropertiesApprovalSyncFunction
  PropertiesApprovalSyncFunctionArn:
    Value: !GetAtt PropertiesApprovalSyncFunction.Arn

  ContractExistsCheckerFunctionName:
    Value: !Ref ContractExistsCheckerFunction
  ContractExistsCheckerFunctionArn:
    Value: !GetAtt ContractExistsCheckerFunction.Arn

  ContentIntegrityValidatorFunctionName:
    Value: !Ref ContentIntegrityValidatorFunction
  ContentIntegrityValidatorFunctionArn:
    Value: !GetAtt ContentIntegrityValidatorFunction.Arn

  WaitForContractApprovalFunctionName:
    Value: !Ref WaitForContractApprovalFunction
  WaitForContractApprovalFunctionArn:
    Value: !GetAtt WaitForContractApprovalFunction.Arn

  #### STEPFUNCTIONS OUTPUTS
  ApprovalStateMachineName:
    Value: !GetAtt ApprovalStateMachine.Name
  ApprovalStateMachineArn:
    Value: !Ref ApprovalStateMachine

  #### EVENT BRIDGE OUTPUTS
  UnicornPropertiesEventBusName:
    Value: !GetAtt UnicornPropertiesEventBus.Name

  #### CLOUDWATCH LOGS OUTPUTS
  UnicornPropertiesCatchAllLogGroupArn:
    Description: Log all events on the service's EventBridge Bus
    Value: !GetAtt UnicornPropertiesCatchAllLogGroup.Arn

  ApprovalStateMachineLogGroupName:
    Value: !Ref ApprovalStateMachineLogGroup
