name: Build and Test

on:
  push:
    branches: [develop, main]
    paths:
      - '.github/workflows/*'
      - 'unicorn_contracts/**'
      - 'unicorn_properties/**'
      - 'unicorn_web/**'
  pull_request:
    branches: [develop, main]
    paths:
      - './github/workflows/*'
      - 'unicorn_contracts/**'
      - 'unicorn_properties/**'
      - 'unicorn_web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [unicorn_contracts, unicorn_properties, unicorn_web]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: |
        npm ci 
        npm run build
        npm test
      working-directory: ${{ matrix.folder }}