name: Build & Test Workflow
on:
  push:
    branches: [develop, main, v2]
    paths:
      - '.github/workflows/*'
      - 'unicorn_contracts/**'
      - 'unicorn_properties/**'
      - 'unicorn_web/**'
  pull_request:
    branches: [develop, main, v2]
    paths:
      - './github/workflows/*'
      - 'unicorn_contracts/**'
      - 'unicorn_properties/**'
      - 'unicorn_web/**'

env:
  AWS_REGION : "ap-southeast-2"

permissions:
  id-token: write
  contents: read

jobs:
  service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [unicorn_contracts, unicorn_properties, unicorn_web]
    steps:
    - uses: actions/checkout@v3
    - name: Set NodeJS version
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache-dependency-path: ${{ matrix.folder }}/package-lock.json
        cache: 'npm'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::819998446679:role/GithubActions-ServerlessDeveloperExperience
        aws-region: ${{ env.AWS_REGION }}
    - name: SAM Build, Deploy and Test
      uses: aws-actions/setup-sam@v2
      with: 
        use-installer: true
    - run: |
        npm ci 
        sam build 
        sam deploy --no-confirm-changeset
        make test
      working-directory: ${{ matrix.folder }}